version: 2

models:
  - name: stg_orders
    description: "Staging table for orders, containing raw order information."
    columns:
      - name: order_id
        description: "Unique identifier for the order."
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_order_items')
              field: order_id
      - name: customer_id
        description: "Identifier for the customer who placed the order."
      - name: order_date
        description: "Date when the order was placed."
        tests:
          - not_null
      - name: total_amount
        description: "Total amount spent in the order."
        tests:
          - not_null

  - name: stg_order_items
    description: "Staging table for order items, containing raw details of each product in an order."
    columns:
      - name: order_item_id
        description: "Unique identifier for each order item."
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Identifier for the order."
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        description: "Identifier for the product."
        tests:
          - not_null
      - name: quantity
        description: "Number of units of the product in the order."
        tests:
          - not_null
      - name: price
        description: "Price per unit of the product at the time of purchase."
        tests:
          - not_null

  - name: dim_products
    description: "Dimension table for products, cleaned and standardized."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name of the product."
      - name: category
        description: "Category of the product (e.g., Electronics, Apparel, etc.)."
        tests:
          - accepted_values:
              values: ['Footwear', 'Electronics', 'Kitchen', 'Bags', 'Accessories', 'Apparel']
      - name: price
        description: "Standardized price of the product."
